# Generated by Django 2.0.5 on 2018-07-09 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0002_lesson_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='tutorial_series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutorial', to='tutorial.TutorialSeries'),
        ),
    ]
